### ISSUE TITLE
More precise measurement

### ISSUE THREAD

**Issue by vhotspur** [arahusky/performance_javadoc#18]
Using reflection is okay for the preliminary results but for the most precise ones, the server shall generate the source code executing the method and run it. Maybe even in a new JVM. You might be interested in [this file](http://sourceforge.net/p/spl-tools/code/ci/master/tree/src/java/cz/cuni/mff/spl/deploy/build/measurement.vm) that is used to generate a Java source code on the fly.

**Comment by arahusky** [comment]
Just wondering, is it Apache Velocity, that you use to transform the templates into java source code, or what program? Thanks:)

**Comment by vhotspur** [comment]
Yes, see [Code.java](http://sourceforge.net/p/spl-tools/code/ci/master/tree/src/java/cz/cuni/mff/spl/deploy/build/Code.java).

Other option is to use [jmh](http://openjdk.java.net/projects/code-tools/jmh/).

**Comment by arahusky** [comment]
Added mainly in #fc85c322beeed0f4a69090d5fc8eab194ad34cb2

**Comment by arahusky** [comment]
Added in fc85c322beeed0f4a69090d5fc8eab194ad34cb2

**Comment by arahusky** [comment]
Added mainly in fc85c322beeed0f4a69090d5fc8eab194ad34cb2, code-generating as well in 508e64dffc933016a550f85bae4ca94d44c69276 and some bugs fixed in ddddfab1a8bf4fe87c3055dae0e1b7c9db4e12fc

**Comment by arahusky** [comment]
Added mainly in fc85c322beeed0f4a69090d5fc8eab194ad34cb2, code-generating as well in 508e64dffc933016a550f85bae4ca94d44c69276 and some bugs fixed in ddddfab1a8bf4fe87c3055dae0e1b7c9db4e12fc
